package com.poseidon.model;

public class CitiesEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cities.parent_code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    private String parentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.code
     *
     * @return the value of cities.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.code
     *
     * @param code the value for cities.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.name
     *
     * @return the value of cities.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.name
     *
     * @param name the value for cities.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cities.parent_code
     *
     * @return the value of cities.parent_code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cities.parent_code
     *
     * @param parentCode the value for cities.parent_code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }
}