package com.poseidon.model;

public class MemberEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.member_id
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.nick_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.mobile
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.real_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.email
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.id_card
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_member.gender
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.member_id
     *
     * @return the value of b2c_member.member_id
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.member_id
     *
     * @param memberId the value for b2c_member.member_id
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.nick_name
     *
     * @return the value of b2c_member.nick_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.nick_name
     *
     * @param nickName the value for b2c_member.nick_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.mobile
     *
     * @return the value of b2c_member.mobile
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.mobile
     *
     * @param mobile the value for b2c_member.mobile
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.real_name
     *
     * @return the value of b2c_member.real_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.real_name
     *
     * @param realName the value for b2c_member.real_name
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.email
     *
     * @return the value of b2c_member.email
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.email
     *
     * @param email the value for b2c_member.email
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.id_card
     *
     * @return the value of b2c_member.id_card
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.id_card
     *
     * @param idCard the value for b2c_member.id_card
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_member.gender
     *
     * @return the value of b2c_member.gender
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_member.gender
     *
     * @param gender the value for b2c_member.gender
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
}