package com.poseidon.model;

public class ProvincesEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.code
     *
     * @return the value of provinces.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.code
     *
     * @param code the value for provinces.code
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.name
     *
     * @return the value of provinces.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.name
     *
     * @param name the value for provinces.name
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}