package com.poseidon.model;

import java.util.Date;

public class ResourceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.source_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.source_name
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.open_mode
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String openMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.icon
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.pid
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.seq
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private Byte seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_status
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private Byte resourceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.opened
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private Byte opened;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resource_type
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private Byte resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_time
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.level_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    private String levelId;


    private String sourceUrl;

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.source_id
     *
     * @return the value of resource.source_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.source_id
     *
     * @param sourceId the value for resource.source_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.source_name
     *
     * @return the value of resource.source_name
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.source_name
     *
     * @param sourceName the value for resource.source_name
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.open_mode
     *
     * @return the value of resource.open_mode
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getOpenMode() {
        return openMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.open_mode
     *
     * @param openMode the value for resource.open_mode
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setOpenMode(String openMode) {
        this.openMode = openMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.icon
     *
     * @return the value of resource.icon
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.icon
     *
     * @param icon the value for resource.icon
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.pid
     *
     * @return the value of resource.pid
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.pid
     *
     * @param pid the value for resource.pid
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.seq
     *
     * @return the value of resource.seq
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public Byte getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.seq
     *
     * @param seq the value for resource.seq
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setSeq(Byte seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_status
     *
     * @return the value of resource.resource_status
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public Byte getResourceStatus() {
        return resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_status
     *
     * @param resourceStatus the value for resource.resource_status
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setResourceStatus(Byte resourceStatus) {
        this.resourceStatus = resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.opened
     *
     * @return the value of resource.opened
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public Byte getOpened() {
        return opened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.opened
     *
     * @param opened the value for resource.opened
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setOpened(Byte opened) {
        this.opened = opened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resource_type
     *
     * @return the value of resource.resource_type
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public Byte getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resource_type
     *
     * @param resourceType the value for resource.resource_type
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setResourceType(Byte resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_time
     *
     * @return the value of resource.create_time
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_time
     *
     * @param createTime the value for resource.create_time
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.level_id
     *
     * @return the value of resource.level_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.level_id
     *
     * @param levelId the value for resource.level_id
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId;
    }
}