package com.poseidon.model;

import java.util.Date;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.user_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.login_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.nick_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.cn_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String cnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.en_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.pass_word
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.pass_bulter
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String passBulter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.salt
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.sex
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.age
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.phone
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.user_type
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.user_status
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Byte userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.organization_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b2c_user.create_time
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.user_id
     *
     * @return the value of b2c_user.user_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.user_id
     *
     * @param userId the value for b2c_user.user_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.login_name
     *
     * @return the value of b2c_user.login_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.login_name
     *
     * @param loginName the value for b2c_user.login_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.nick_name
     *
     * @return the value of b2c_user.nick_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.nick_name
     *
     * @param nickName the value for b2c_user.nick_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.cn_name
     *
     * @return the value of b2c_user.cn_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.cn_name
     *
     * @param cnName the value for b2c_user.cn_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.en_name
     *
     * @return the value of b2c_user.en_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.en_name
     *
     * @param enName the value for b2c_user.en_name
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.pass_word
     *
     * @return the value of b2c_user.pass_word
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.pass_word
     *
     * @param passWord the value for b2c_user.pass_word
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.pass_bulter
     *
     * @return the value of b2c_user.pass_bulter
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getPassBulter() {
        return passBulter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.pass_bulter
     *
     * @param passBulter the value for b2c_user.pass_bulter
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setPassBulter(String passBulter) {
        this.passBulter = passBulter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.salt
     *
     * @return the value of b2c_user.salt
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.salt
     *
     * @param salt the value for b2c_user.salt
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.sex
     *
     * @return the value of b2c_user.sex
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.sex
     *
     * @param sex the value for b2c_user.sex
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.age
     *
     * @return the value of b2c_user.age
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.age
     *
     * @param age the value for b2c_user.age
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.phone
     *
     * @return the value of b2c_user.phone
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.phone
     *
     * @param phone the value for b2c_user.phone
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.user_type
     *
     * @return the value of b2c_user.user_type
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.user_type
     *
     * @param userType the value for b2c_user.user_type
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.user_status
     *
     * @return the value of b2c_user.user_status
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.user_status
     *
     * @param userStatus the value for b2c_user.user_status
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.organization_id
     *
     * @return the value of b2c_user.organization_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.organization_id
     *
     * @param organizationId the value for b2c_user.organization_id
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b2c_user.create_time
     *
     * @return the value of b2c_user.create_time
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b2c_user.create_time
     *
     * @param createTime the value for b2c_user.create_time
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}