package com.poseidon.mapper;

import com.poseidon.model.AccountEntity;

public interface AccountEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insert(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insertSelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    AccountEntity selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKeySelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_account
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKey(AccountEntity record);
}