package com.poseidon.mapper;

import com.poseidon.model.AreasEntity;

public interface AreasEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insert(AreasEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insertSelective(AreasEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    AreasEntity selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKeySelective(AreasEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areas
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKey(AreasEntity record);
}