package com.poseidon.mapper;

import com.poseidon.model.CitiesEntity;

public interface CitiesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insert(CitiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insertSelective(CitiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    CitiesEntity selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKeySelective(CitiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKey(CitiesEntity record);
}