package com.poseidon.mapper;

import com.poseidon.model.LoginRecordEntity;

public interface LoginRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insert(LoginRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insertSelective(LoginRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    LoginRecordEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKeySelective(LoginRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_login_record
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKey(LoginRecordEntity record);
}