package com.poseidon.mapper;

import com.poseidon.model.MemberEntity;

public interface MemberEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insert(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int insertSelective(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    MemberEntity selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKeySelective(MemberEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_member
     *
     * @mbggenerated Tue Aug 22 14:46:43 CST 2017
     */
    int updateByPrimaryKey(MemberEntity record);
}