package com.poseidon.mapper;

import com.poseidon.model.ProvincesEntity;

public interface ProvincesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insert(ProvincesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insertSelective(ProvincesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    ProvincesEntity selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKeySelective(ProvincesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provinces
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKey(ProvincesEntity record);
}