package com.poseidon.mapper;

import com.poseidon.model.ResourceEntity;

public interface ResourceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    int deleteByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    int insert(ResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    int insertSelective(ResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    ResourceEntity selectByPrimaryKey(String sourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    int updateByPrimaryKeySelective(ResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Wed Sep 06 14:18:50 CST 2017
     */
    int updateByPrimaryKey(ResourceEntity record);
}