package com.poseidon.mapper;

import com.poseidon.model.StreetsEntity;

public interface StreetsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insert(StreetsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int insertSelective(StreetsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    StreetsEntity selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKeySelective(StreetsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table streets
     *
     * @mbggenerated Tue Aug 22 15:02:37 CST 2017
     */
    int updateByPrimaryKey(StreetsEntity record);
}