package com.poseidon.mapper;

import com.poseidon.model.UserEntity;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    UserEntity selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b2c_user
     *
     * @mbggenerated Tue Sep 05 15:53:42 CST 2017
     */
    int updateByPrimaryKey(UserEntity record);
}